### PR TITLE
Adjust string length for fullwidth characters when `end` is undefined

### LINKED ISSUE #26: Lose characters when fullwidth characters exist and end is not specified
[Issuehunt badges](https://issuehunt.io/r/chalk/slice-ansi/issues/26)

Lose characters when there are fullwidth characters in the string and the third argument `end` is not specified:
```javascript
const str = sliceAnsi("古古test", 0);
// => '古古te'
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Submitted pull Requests
- [#29 supports fullwidth characters & not specified end](https://issuehunt.io/r/chalk/slice-ansi/pull/29)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/chalk/slice-ansi/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by kevva**
Fixes #26.
Closes #29.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@TiagoDanin Can you help review?

**Comment by Qix-** [comment]
Can we add a few cases where `string.normalize()` would change the input string, too? I want to make sure that won't break anything.

**Comment by kevva** [comment]
Good catch, that actually breaks stuff. I wrote the code that included the normalization, but now that I think of it, I don't see why we need it. It'll only modify the string to use a different character than the one inputted. Also, all the tests passes without normalization as well.

```js
'\u006E\u0303test' === '\u006E\u0303test'.normalize();
//=> false
```

**Comment by Qix-** [comment]
I agree, we shouldn't care about it. It's another linear sweep of the string, anyway, so it's a win-win. Let's remove it ^^

**Comment by kevva** [comment]
I'll do it in a separate PR though since it's unrelated to this.

**Comment by TiagoDanin** [comment]
I found a big problem.
The support fullwidth characters ( #4, #9) does not work with ANSI combination.

DeepinScreenshot_select-area_20190920220205

`\u001B[31m古古test\u001B[39m` does not return the `\u001B[31m`

**Comment by kevva** [comment]
@TiagoDanin, could you provide a test example?
```

**Comment by TiagoDanin** [comment]
```js
test.failing('fullwidth characters + ANSI codes', t => {
	t.is(sliceAnsi('\u001B[31m古古test\u001B[39m', 3), '\u001B[31m古test\u001B[39m');
	t.is(sliceAnsi('\u001B[31m古古test\u001B[39m', 3, 4), '\u001B[31m古\u001B[39m');
});
```

**Comment by kevva** [comment]
@TiagoDanin, that's no bug, you're starting to slice in the middle of a full width character. This works:

```js
t.is(sliceAnsi('\u001B[31m古古test\u001B[39m', 2), '\u001B[31m古test\u001B[39m');
t.is(sliceAnsi('\u001B[31m古古test\u001B[39m', 2, 4), '\u001B[31m古\u001B[39m');
```

**Pull request merged**
